<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getUsers(): array
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('u.id, u.username, u.disabled')
            ->from('UserBundle:User', 'u')
        ;

        return $qb->getQuery()->getResult();
    }
}
